version: "3.7"

services:
  lnserver:
    container_name: lnpaywall-lnserver
    image: node:lts-alpine
    volumes:
      - ./lnserver:/app
    working_dir: /app
    command: sh -c 'npm install && npm run dev'
    networks:
      - ln-network
      - paywall-network
    expose:
      - 8080

  backend:
    container_name: lnpaywall-authbackend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '1000'
    image: sail-8.2/app
    expose:
      - 80
    ports:
      - 3000:80
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      WWWUSER: '1000'
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    restart: unless-stopped
    command: sh -c 'composer install && php -d variables_order=EGPCS artisan serve --host 0.0.0.0 --port 80'
    networks:
      - paywall-network

  nginx:
    container_name: lnpaywall-proxy
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
    ports:
      - 80:80
    restart: unless-stopped
    environment:
      FRONTEND: "${FRONTEND}"
    working_dir: /etc/nginx
    command: sh -c "envsubst '$$FRONTEND' < nginx.conf.template > nginx.conf && nginx -g 'daemon off;'"
    networks:
      - paywall-network
      - frontend-network

networks:
  ln-network:
    name: ${LN_NETWORK}
    external: true
  frontend-network:
    name: ${FRONTEND_NETWORK}
    external: true
  paywall-network:
    driver: bridge
    internal: true

