version: "3.7"
services:
  frontend:
    image: evop/static_webserver
    restart: unless-stopped
    volumes:
      - ${APP_DIR}:/app:ro

  # backend:
  #   image: python:3.6
  #   volumes:
  #     - ./backend:/app
  #   working_dir: /app 
  #   command: python main.py
  #   expose:
  #     - 3000

  lnserver:
    image: node:lts-alpine
    volumes:
      - ./lnserver:/app
    working_dir: /app
    command: npm run dev
    networks:
      - polar
      - default
    ports:
      - 8080:8080

  backend:
    build:
      context: ./larabackend/vendor/laravel/sail/runtimes/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '1000'
    image: sail-8.2/app
    expose:
      - 80
    ports:
      - 3000:80
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      WWWUSER: '1000'
      LARAVEL_SAIL: 1
    volumes:
      - ./larabackend:/var/www/html
    restart: unless-stopped
    command: php -d variables_order=EGPCS /var/www/html/artisan serve --host 0.0.0.0  --port 80
    networks:
      - default

  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - default

networks:
  polar:
    name: polar-network-1_default
    external: true
  default:
    driver: bridge
