version: "3.7"

services:
  lnserver:
    container_name: lnpaywall-lnserver
    image: node:lts-alpine
    volumes:
      - ./lnserver:/app
    working_dir: /app
    command: sh -c 'npm install && npm run dev'
    networks:
      - ln-network
      - paywall-network
    expose:
      - 8080

  backend:
    container_name: lnpaywall-authbackend
    build:
      context: ./laravel_sail_8-3
      args:
        WWWGROUP: '1000'
    image: sail-8.2/app
    expose:
      - 80
    ports:
      - 80:80
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      WWWUSER: '1000'
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    restart: unless-stopped
    command: sh -c 'composer install && php -d variables_order=EGPCS artisan serve --host 0.0.0.0 --port 80'
    networks:
      - paywall-network
      - frontend-network

networks:
  ln-network:
    name: ${LN_NETWORK}
    external: true
  frontend-network:
    name: ${FRONTEND_NETWORK}
    external: true
  paywall-network:
    driver: bridge
    internal: true

