version: "3.7"

services:
  lnserver:
    container_name: lnpaywall-lnserver
    image: node:lts-alpine
    volumes:
      - ./lnserver:/app
    working_dir: /app
    command: sh -c 'npm install && npm run dev'
    networks:
      - ln-network
      - paywall-network
    expose:
      - 8080

  backend:
    container_name: lnpaywall-backend
    build:
      context: ./backend/docker
    image: lnpaywall-backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - paywall-network
      - frontend-network

networks:
  ln-network:
    name: ${LN_NETWORK}
    external: true
  frontend-network:
    name: ${FRONTEND_NETWORK}
    external: true
  paywall-network:
    driver: bridge
    internal: true
