version: "3.7"
services:
  frontend:
    image: evop/static_webserver
    restart: unless-stopped
    volumes:
      - ${APP_DIR}:/app:ro

  lnserver:
    image: node:lts-alpine
    volumes:
      - ./lnserver:/app
    working_dir: /app
    command: sh -c 'npm install && npm run dev'
    networks:
      - ln-network
      - default
    ports:
      - 8080:8080

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '1000'
    image: sail-8.2/app
    expose:
      - 80
    ports:
      - 3000:80
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      WWWUSER: '1000'
      SOMEENV: 'somevalue'
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    restart: unless-stopped
    command: sh -c 'composer install && php -d variables_order=EGPCS artisan serve --host 0.0.0.0 --port 80'
    networks:
      - default

  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - default

networks:
  ln-network:
    name: ${LN_NETWORK}
    external: true
  default:
    driver: bridge
